config/routes.rb
Rails.application.routes.draw do
  root :to =>'list#index'
  # root :to =>'sessions#new'

  # 新規登録画面パス
  resource :user, only: [:new, :edit, :create]

  # ログインパス
  get 'login',  to: 'sessions#new', as: 'new_sessions'
  post 'login', to: 'sessions#create', as: 'create_sessions'
  delete 'logout', to: 'sessions#destroy', as: 'destroy_sessions'

  # 試験パス
  get 'list/index', to: 'list#index', as: 'index_list'
  get 'test/play', to: 'test#play', as: 'play_test'
  get 'test/check', to: 'test#check', as: 'check_test'
  post 'editing/new', to: 'editing#new', as: 'new_editing'
  post 'editing/edit', to: 'editing#edit', as: 'edit_editing'
end

app/models/answer.rb
class Answer < ApplicationRecord
    has_many :problems, foreign_key: 'answer_id', dependent: :destroy
  
    validates :answer, presence: true, length: { maximum: 2 }
    validates :commentary, presence: true, length: { maximum: 500 }
end  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
    belongs_to :question, class_name: 'Problem', foreign_key: 'questions_id'
  
    validates :choice, presence: true, numericality: { only_integer: true }
    validates :content, presence: true, length: { maximum: 100 }
end  

app/models/department.rb
class Department < ApplicationRecord
    has_many :users, foreign_key: 'department_id', dependent: :destroy # 部門に所属するユーザーたち
  
    validates :department, presence: true, length: { maximum: 20 }
  end
  

app/models/exam.rb
class Exam < ApplicationRecord
    belongs_to :respondent, class_name: 'User', foreign_key: 'respondent_id'
    belongs_to :question, class_name: 'Problem', foreign_key: 'questions_id'
  
    validates :questions_num, presence: true, numericality: { only_integer: true }
    validates :answer_num, presence: true, numericality: { only_integer: true }
    validates :user_answer, allow_nil: true, length: { maximum: 2 }
end
  

app/models/exam_type.rb
class ExamType < ApplicationRecord
    has_many :problems, foreign_key: 'qualifications_id', dependent: :destroy
  
    validates :qualification, presence: true, length: { maximum: 20 }
end

app/models/examtype.rb
# class ExamType < ApplicationRecord
#     has_many :problems, foreign_key: 'qualifications_id', dependent: :destroy
  
#     validates :qualification, presence: true, length: { maximum: 20 }
# end  

# コマンドで消せない...

app/models/problem.rb
class Problem < ApplicationRecord
    belongs_to :author, class_name: 'User', foreign_key: 'author_id'
    belongs_to :qualification, class_name: 'ExamType', foreign_key: 'qualifications_id'
    belongs_to :answer, class_name: 'Answer', foreign_key: 'answer_id'
  
    has_many :choices, foreign_key: 'questions_id', dependent: :destroy
    has_one :exam, foreign_key: 'questions_id', dependent: :destroy # 1対1の関連付け
  
    validates :questions, presence: true, length: { maximum: 200 }
  end
  

app/models/user.rb
class User < ApplicationRecord
  self.primary_key = 'number'

  belongs_to :department
  has_many :exams, foreign_key: 'respondent_id', dependent: :destroy
  has_many :problems, foreign_key: 'author_id', dependent: :destroy

  # 仮想属性として re_password を定義
  attr_accessor :re_password

  validates :name, presence: true, length: { maximum: 20 }
  validates :number, presence: true, uniqueness: true, length: { is: 6 }
  validates :password, presence: true, numericality: { only_integer: true }, length: { is: 6 }

  # password と re_password が一致することを確認するバリデーション
  validate :passwords_match

  private

  def passwords_match
    if password != re_password
      errors.add(:re_password, "とパスワードが一致しません")
    end
  end
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/editing_controller.rb
class EditingController < ApplicationController
    def edit
    end

    def new
    end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
    before_action :current_user
 
    def index
      # 問題db（表示）
      @problem = Problem.new
      @problems = Problem.all.order(created_at: :desc)
  
      # 資格種類db（表示）
      # @exam_type = Exam_type.new
      # @exam_types = Exam_type.all.order(created_at: :desc)
    end
   
    def create
      # 問題作成
    end
  
    def destroy
      # 問題削除
    end
   
    private
    
    def current_user
      if session[:department]
        @user = User.find(session[:department])
      else
        flash[:alert] = "ログインする必要があります。"
        redirect_to new_sessions_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in?, only: [:new, :create]
 
  def new
    
  end

  def create
      @user = User.find_by(department: params[:department], password: params[:password])
      if @user
          session[:department] = @user.department
          flash[:notice] = "ログインに成功しました。"
          redirect_to memos_path
      else
          flash[:alert] = "ログインに失敗しました。"
          render action: "new"
      end
  end

  def destroy
      session[:department] = nil
      redirect_to new_sessions_path
  end

  private

  def logged_in?
      if session[:department]
          @user = User.find(session[:department])
          flash[:notice] = "すでにログインしています。"
          redirect_to memos_path
      end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
    def play
        
    end

    def check

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user_new = User.new
        # 学科情報を取得
        @departments = Department.pluck(:department, :id) # :department と :id を配列で取得
      end

    def edit
    end

    def create
        @user_new = User.new(user_params)

        # パスワードと確認用パスワードが一致するか確認
        # if @user_new.password == @user_new.re_password
            if @user_new.save
                session[:number] = @user_new.number
                flash[:notice] = "アカウントを作成しました。"
                redirect_to index_list_path
            else
                flash.now[:alert] = "アカウント作成に失敗しました。"
                render action: "new"
            end
        # else
        #     flash.now[:alert] = "パスワードが一致しません。再度、入力をお願いします。"
        #     render action: "new"
        # end
    end

    def update
        @user_new = User.find(params[:id])

        # 更新処理が必要な場合はここで適切に処理を記述
        if @user_new.update(user_params)
            flash[:notice] = "アカウント情報を更新しました。"
            redirect_to index_list_path
        else
            flash.now[:alert] = "アカウント情報の更新に失敗しました。"
            render action: "edit"
        end
    end

    private

    def user_params
        
        user_params = params.permit(:name, :department, :number, :password, :re_password)
        
        # department を整数に変換
        user_params["department"] = user_params["department"].to_i
        user_params[:password] = user_params[:password].to_i
        user_params[:re_password] = user_params[:re_password].to_i
      
        # 変換後のパラメータを確認
        puts "After conversion: #{user_params["department"]}"

        if user_params[:department] == 6
            # it = Department.find_by(department: "IT学科")
            user_params[:department_id] = Department.find_by(department: "IT学科").id
            protect_from_forgery :except => [:department_id]
        end
        user_params.permit(:name, :department_id, :number, :password, :re_password)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/editing_helper.rb
module EditingHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/editing/_form.html.erb
<body>
<div class="container">
    <h1>試験名</h1>

    <div class="question-section">
    <%= label_tag :question_text, "問題文" %>
    <%= text_area_tag :question_text, nil, rows: 4, id: "question-text" %>
    </div>

    <div class="choices-section">
    <%= label_tag :choices, "選択肢" %>
    <div class="choices">
        <div class="choice">
        <span>1</span>
        <%= text_field_tag :choice_1, nil %>
        <%= button_tag "×", class: "delete-btn" %>
        </div>
        <div class="choice">
        <span>2</span>
        <%= text_field_tag :choice_2, nil %>
        <%= button_tag "×", class: "delete-btn" %>
        </div>
        <div class="choice">
        <span>3</span>
        <%= text_field_tag :choice_3, nil %>
        <%= button_tag "○", class: " correct-btn" %>
        </div>
    </div>
    <%= button_tag "＋", class: "add-btn" %>
    </div>

    <div class="explanation-section">
    <%= label_tag :explanation, "解説" %>
    <%= text_area_tag :explanation, nil, rows: 4, id: "explanation" %>
    </div>


</div>
</body>

app/views/editing/edit.html.erb
<h2>修正</h2>
<%= render "form" %>
<%= button_to '修正',index_list_path,method: :get,class: "submit-btn" %>

app/views/editing/new.html.erb
<h2>新規登録</h2>
<%= render "form" %>
 <%= button_to '登録',index_list_path,method: :get, class: "submit-btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/list/index.html.erb
<%= stylesheet_link_tag 'list', :media => "all" %>

<h1>試験名</h1>
<div class="container">
  <div class="exam-select">
    <label for="pet-select">試験一覧</label>
    <select name="pets" id="pet-select">
      <option value="">ああああ</option>
      <option value="dog">Dog</option>
      <option value="cat">Cat</option>
      <option value="hamster">Hamster</option>
      <option value="parrot">Parrot</option>
      <option value="spider">Spider</option>
      <option value="goldfish">Goldfish</option>
    </select>
  </div>

  <div class="exam-header">
    <%= button_to '問題登録',new_editing_path, class: 'btn-register' %>
  </div>

  <div class="exam-list">
    <% 5.times do %> <!-- サンプルとして5つのアイテムを表示 -->
  
  <%= link_to play_test_path, class: 'question-item' do %>
  <div class="question-info">
    <span>問題名</span>
    <span>学生番号 / 作成日</span>
  </div>
  <div class="buttons">
  <%= button_to '編集',edit_editing_path, class: 'btn-edit' %>
  <%= button_to '削除',index_list_path,method: :get, class: 'btn-delete' %>
  </div>
<% end %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="new_form_box">
  <div>
    <h1>ロゴ</h1>
  </div>
  <h2>新規登録画面</h2>
  <%= form_with url: user_path, url:user_path, local: true, method: :post do |f| %>
    <div class="form_box">
      <%= f.label :name, "氏名" %>
      <%= f.text_field :name, placeholder: "例）山田太郎", class: "text_box" %>
    </div>

    <div class="form_box">
      <%= f.label :department, "学科名" %>
      <%= f.select :department, @departments, {prompt: "選択してください"}, class: "text_box", id: "department_id" %>
    </div>

    <div class="form_box">
      <%= f.label :number, "ID/学籍番号" %>
      <%= f.text_field :number, placeholder: "例）JR0000", class: "text_box" %>
    </div>

    <div class="form_box">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, placeholder: "半角数字:6文字", class: "text_box" %>
    </div>

    <div class="form_box">
        <%= f.label :re_password, "パスワード（確認）" %>
        <%= f.password_field :re_password, placeholder: "もう一度、入力をお願いします", class: "text_box" %>
    </div>

    <%= f.submit "登録", class: "btn" %>
  <% end %>
</div>